import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]
[window]
dynamic_padding = true
blur = true
dynamic_title = true

[font]
normal = { family = "Iosevka Term SS14 Extended", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true
